apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
      - name: angular-app
        image: tahermzid/frontend_devops:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4201
        command: ["ng","serve","--host","0.0.0.0","--port","4201"]
        env:
        - name: url
          value: http://172.29.18.50:31003/SpringMVC

